global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '${SMTP_EMAIL}'
  smtp_auth_username: '${SMTP_EMAIL}'
  smtp_auth_password: '${SMTP_PASSWORD}'

route:
  receiver: 'default-receiver'

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: '${ALERT_EMAIL_TO}'
