services:
## Prometheus
  prometheus:
    container_name: prometheus
    restart: always    
    build: ./prometheus
    #image: prom/prometheus
    #volumes:
    #  - ./prometheus/:/etc/prometheus/
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 9090:9090
    networks:
      - monitor-net

## Alertmanager
  alertmanager:
    container_name: alertmanager
    restart: always
    build: ./alertmanager
    #image: prom/alertmanager
    #volumes:
    #  - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    environment:
      - SMTP_EMAIL=${SMTP_EMAIL:-example@email.com}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-examplepassword}
      - ALERT_EMAIL_TO=${ALERT_EMAIL_TO:-example@email.com}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "9093:9093"
    networks:
      - monitor-net

## Grafana
  grafana:
    container_name: grafana
    restart: always
    build: ./grafana
    #image: grafana/grafana
    #volumes:
      #- ./grafana/grafana.ini:/etc/grafana/grafana.ini
      #- ./grafana/grafana.db:/var/lib/grafana/grafana.db
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - SMTP_EMAIL=${SMTP_EMAIL:-example@email.com}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-examplepassword}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 3000:3000
    networks:
      - monitor-net

## Loki
  loki:
    container_name: loki
    restart: always
    build: ./loki
    #image: grafana/loki:latest
    #volumes:
    #  - ./loki/config-loki.yml:/etc/loki/config-loki.yml
    command: -config.file=/etc/loki/config-loki.yml
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 3100:3100
    networks:
      - monitor-net

networks:
  monitor-net:
